# some general config here
# be careful: yaml does not allow tabs. only spaces.

listeners_url: "http://stream.reliveradio.de:8000/json.xsl"
artwork_base_url: "http://static.reliveradio.de/logos/"

mix:
  desktop_stream_url: "http://stream.reliveradio.de:8000/24.mp3"
  mobile_stream_url: "http://stream.reliveradio.de:8000/24mobile.mp3"
  airtime_url: "http://mixzentrale.reliveradio.de/api/upcoming-info"

technique:
  desktop_stream_url: "http://stream.reliveradio.de:8000/technik.mp3"
  mobile_stream_url: "http://stream.reliveradio.de:8000/technikmobile.mp3"
  airtime_url: "http://technikzentrale.reliveradio.de/api/upcoming-info"

culture:
  desktop_stream_url: "http://stream.reliveradio.de:8000/kultur.mp3"
  mobile_stream_url: "http://stream.reliveradio.de:8000/kulturmobile.mp3"
  airtime_url: "http://kulturzentrale.reliveradio.de/api/upcoming-info"