# some general config here
# be careful: yaml does not allow tabs. only spaces.

listeners_url: "http://stream.reliveradio.de:8000/json.xsl"
artwork_base_url: "http://static.reliveradio.de/logos/"

mix:
  desktop_stream_url: "http://newapi.reliveradio.de:8000/mp3_128"
  mobile_stream_url: "http://newapi.reliveradio.de:8000/mp3_48"
  airtime_url: "http://newapi.reliveradio.de/api/upcoming-info"

technique:
  desktop_stream_url: "http://newapi.reliveradio.de:8000/mp3_128"
  mobile_stream_url: "http://newapi.reliveradio.de:8000/mp3_48"
  airtime_url: "http://newapi.reliveradio.de/api/upcoming-info"

culture:
  desktop_stream_url: "http://newapi.reliveradio.de:8000/mp3_128"
  mobile_stream_url: "http://newapi.reliveradio.de:8000/mp3_48"
  airtime_url: "http://newapi.reliveradio.de/api/upcoming-info"